# Generated by Django 3.0.7 on 2021-02-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='apellidos',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='sexo',
            new_name='sex',
        ),
    ]
