# Generated by Django 3.0.7 on 2021-02-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20210218_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Person',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id']},
        ),
    ]
